/** Единые контакты (NAP) — использовать везде одинаково */
export const SITE = {
  name: "ООО «АЙБАЗА»",
  shortName: "АЙБАЗА",
  phone: "+7 (347) 200-00-00",
  phoneHref: "tel:+73472000000",
  whatsapp: "https://wa.me/79370000000",
  telegram: "https://t.me/aybaza_ufa",
  email: "info@aybaza.ru",
  address: {
    street: "ул. Ленина, 45, офис 312",
    city: "Уфа",
    region: "Республика Башкортостан",
    postalCode: "450000",
    full: "г. Уфа, ул. Ленина, 45, офис 312",
  },
  hours: "Пн–Вс 9:00–21:00",
  geo: { lat: 54.7351, lng: 55.9587 },
  serviceArea: [
    "Уфа",
    "Стерлитамак",
    "Салават",
    "Нефтекамск",
    "Октябрьский",
    "Туймазы",
    "Белорецк",
    "Ишимбай",
    "Сибай",
    "Кумертау",
  ],
  stats: {
    cars: "340+",
    years: "4",
    cities: "10+",
  },
} as const;
