/** Единые контакты (NAP) — использовать везде одинаково */
export const SITE = {
  name: "ООО «АЙБАЗА»",
  shortName: "АЙБАЗА",
  phone: "+7 (961) 369-66-99",
  phoneHref: "tel:+79613696699",
  whatsapp: "https://wa.me/79613696699",
  telegram: "https://t.me/aybaza_ufa",
  email: "info@aybaza.ru",
  address: {
    street: "ул. Интернациональная, 64",
    city: "Уфа",
    region: "Республика Башкортостан",
    postalCode: "450068",
    full: "г. Уфа, ул. Интернациональная, 64",
  },
  hours: "Пн–Пт: 9:00–18:00, Сб: 10:00–15:00",
  geo: { lat: 54.7351, lng: 55.9587 },
  serviceArea: [
    "Уфа",
    "Стерлитамак",
    "Салават",
    "Нефтекамск",
    "Октябрьский",
    "Туймазы",
    "Белорецк",
    "Ишимбай",
    "Сибай",
    "Кумертау",
  ],
  stats: {
    cars: "340+",
    years: "4",
    cities: "10+",
  },
} as const;
